version: "3.9"
services:
  discord_bot:
    command: [ "python3", "-u", "discord_bot.py"]
    build: .
    env_file:
    - .env
    depends_on: 
    - redis
    - tiktok_bot
  tiktok_bot:
    command: [ "python3", "-u", "tiktok_bot.py"]
    build: .
    env_file:
    - .env
  redis:
    image: "redis:alpine"
  